# -*- coding: utf-8 -*-
# Excel/表单 英文->中文 翻译字典。规格代码/牌号/件号/纯数字 不收录(保留原文)。
T = {
# —— 缩写/角色/短标签 ——
"A": "A=认可(Acceptance)", "R": "R=负责(Responsible)", "CN": "变更通知(CN)",
"DV": "设计验证(DV)", "ED": "工程设计(ED)", "NA": "不适用", "NO": "否", "No": "否",
"PS": "工艺签核(PS)", "PT": "样件(工装件)", "PV": "工艺验证(PV)", "VP": "量产验证(VP)",
"CAD": "CAD(计算机辅助设计)", "CAE": "CAE(计算机辅助工程)", "DMA": "数字样机装配(DMA)",
"FCA": "FCA(克莱斯勒母公司)", "FDV": "功能开发车(骡车)", "HoQ": "质量屋(HoQ)",
"Qty": "数量", "QTY": "数量", "TBD": "待定", "VOC": "客户之声(VOC)", "YES": "是", "Yes": "是",
"APQP": "先期产品质量策划(APQP)", "Beta": "Beta样", "CODE": "代码", "Comp": "零件级(Comp)",
"Cost": "费用", "DATE": "日期", "Date": "日期", "None": "无", "Odor": "气味",
"P/N:": "件号:", "PLAN": "计划", "PPAP": "生产件批准(PPAP)", "Role": "角色",
"test": "测试", "Time": "时间", "Type": "类型", "TYPE": "类型",
"Alpha": "Alpha样", "CLASS": "类别", "COLOR": "颜色", "Compl": "完成",
"DATE:": "日期:", "DFMEA": "设计FMEA", "DV\nPV": "DV/PV", "Event": "事件",
"FINAL": "最终", "FTE's": "全职人力(FTE)", "Gamma": "Gamma样", "GLOSS": "光泽",
"Hours": "工时", "LOT #": "批次号", "Notes": "备注", "NOTES": "备注", "Other": "其它",
"PFMEA": "过程FMEA", "PHONE": "电话", "Pilot": "试产(Pilot)", "Stage": "阶段",
"Start": "开始", "START": "开始", "Tests": "测试", "Total": "合计",
"ANNUAL": "年度", "Buckle": "带扣 Buckle", "Dept.:": "部门:", "FCA US": "FCA US(克莱斯勒美国)",
"FINISH": "表面处理", "MASTER": "标准样(Master)", "NUMBER": "编号", "Pre-VP": "量产前验证(Pre-VP)",
"RESULT": "结果", "Sample": "样件", "SAMPLE": "样件", "Step 2": "第2步", "Step 3": "第3步",
"Step 5": "第5步", "SUBMIT": "提交", "System": "系统", "Purpose": "目的", "REMARKS": "备注",
"Vehicle": "车型", "Virtual": "虚拟", "Week of": "周(起始)", "Comments": "备注",
"Hardness": "硬度", "Item\nNo.": "序号", "MATERIAL": "材料", "Not Done": "未完成",
"Per spec": "按规范", "per Test": "按测试", "QUANTITY": "数量", "STANDARD": "标准",
"Supplier": "供应商", "SUPPLIER": "供应商", "APPROVALS": "审批", "ATTRIBUTE": "属性检验",
"Burn Rate": "燃烧速率", "Designers": "设计员", "Engineers": "工程师", "Fasteners": "紧固件",
"FCA Plant": "FCA 工厂", "PER MONTH": "每月", "PER SETUP": "每次调机", "Pre-Pilot": "预试产",
"Revision:": "版本:", "STOPLIGHT": "红绿灯状态", "Surrogate": "替代数据", "TEST PLAN": "测试计划",
"Test Plan": "测试计划", "Test Type": "测试类型", "Thickness": "厚度", "Total Eng": "工程合计",
"% COMPLETE": "完成百分比", "COLOR CODE": "颜色代码", "COMPONENT": "零件", "COMPONENT:": "零件:",
"DVP&R No.:": "DVP&R 编号:", "FCA US LLC": "FCA US LLC", "Feas Brief": "可行性简报",
"HAND TOOLS": "手动工具", "ISSUE DATE": "签发日期", "List parts": "列出零件", "MODEL YEAR": "年款",
"Part Name:": "零件名称:", "PRODUCTION": "量产", "Regulatory": "法规", "Sub-System": "子系统",
"Test\nPhase": "测试阶段", "TEST PHASE": "测试阶段", "TEST RESP.": "测试责任方", "Test Type:": "测试类型:",
"Total FTEs": "全职人力合计", "Total Tech": "技术合计", "Validation": "验证",
"All samples": "全部样件", "Description": "描述", "Engineering": "工程",
"Grand Total": "总计", "Must comply": "须符合", "Orig. Date:": "初始日期:",
"Return to :": "返回至:", "SAMPLE SIZE": "样本量", "Team Roster": "团队名单", "Test Phase:": "测试阶段:",
"Test Report": "测试报告", "Total Hours": "总工时", "Traceability": "可追溯性", "Weekly Total": "周合计",
"Actual Timing": "实际时间", "ACTUAL TIMING": "实际时间", "Allocated Fee": "分配费用",
"Annual Volume": "年用量", "Change Notice": "变更通知", "Job 1 Offline": "量产首件下线(Job1)",
"List by role:": "按角色列出:", "Monthly Total": "月合计", "MY / Program:": "年款/项目:",
"No BSR issues": "无异响(BSR)问题", "No inspection": "免检", "Project Scope": "项目范围",
"Stay Retained": "保持固定不脱落", "SUPPLIER NAME": "供应商名称", "Supplier Name": "供应商名称",
"SUPPLIER: TBD": "供应商:待定", "VARIABLE DATA": "计量数据",
"BSR Evaluation": "异响(BSR)评估", "COMPONENT NAME": "零件名称", "CORD-ELASTOMER": "绳-弹性体",
"CREATION DATE:": "创建日期:", "Firm Feel Test": "硬挺手感测试", "Fit and Finish": "配合与外观",
"PER SUBMISSION": "每次提交", "PLANNED TIMING": "计划时间", "Planned Timing": "计划时间",
"Source Package": "采购包(Source Package)", "100% Inspection": "全检", "5 at each temp.": "每个温度5件",
"APPROVAL STATUS": "审批状态", "EVALUATION TYPE": "评估类型", "INITIALS / DATE": "签名缩写/日期",
"PART NAME/DESC:": "零件名称/描述:", "PER BUILD PHASE": "每个生产阶段", "Process Control": "过程控制",
"Submission Date": "提交日期", "VEHICLE CODE(S)": "车型代码", "Check inspection": "抽检",
"Color Evaluation": "颜色评估", "FCA US LLC Buyer": "FCA US 采购员", "Gloss Evaluation": "光泽评估",
"House of Quality": "质量屋(HoQ)", "Important Notes:": "重要提示:", "Overhead Console": "顶置控制台",
"PART NUMBER: TBD": "件号:待定", "Releasing Engr.:": "发布工程师:", "Spending Summary": "费用汇总",
"SUPPLIER CONTACT": "供应商联系人", "Years Experience": "从业年限", "Change Level:  AA": "更改级别:AA",
"CONSTRUCTION: TBD": "结构:待定", "Date role engages": "角色介入日期", "Duty Cycle Tests:": "工作循环测试:",
"Physical Location": "实际地点", "Push Through Test": "推穿测试", "RAW MATERIAL TYPE": "原材料类型",
"Responsible SCIE:": "责任SCIE:", "Supplier Contact:": "供应商联系人:", "System:  Interior": "系统:内饰",
"to write the name": "填写姓名",
# —— 中等长度标签/表头 ——
"Hourly Rate ($/Hr)": "小时费率($/小时)", "MILESTONE / TIMING": "里程碑/时间",
"MR Budgeted Amount": "MR 预算金额", "Task and Functions": "任务与职能",
"Design Verification": "设计验证(DV)", "ED&D Spending Curve": "ED&D 费用曲线",
"FCA US LLC Engineer": "FCA US 工程师", "General Information": "基本信息",
"Maintain Appearance": "保持外观", "Pass/Fail per Spec.": "按规范判定合格/不合格",
"RR Document Purpose": "RR 文件目的", "Sampling inspection": "抽样检验",
"Software Developers": "软件开发人员", "SQ SPECIALIST / SQE": "供应商质量专员/SQE",
"STAGE OF INSPECTION": "检验阶段", "Tensile Strength, N": "拉伸强度(N)",
"Test\nResponsibility": "测试责任方", "TYPE OF PROPERTIES:": "属性类型:",
"CATEGORY DESCRIPTION": "类别说明", "Date role disengages": "角色退出日期",
"Develop system DFMEA": "编制系统 DFMEA", "ED&D Tracking Number": "ED&D 跟踪号",
"GEOMETRIC TOLERANCES": "几何公差", "Material Level spec:": "材料级规范:",
"Project Description:": "项目描述:", "Salary fully Fringed": "含福利的全额薪资",
"Supplier to Complete": "由供应商填写", "Dimensional Stability": "尺寸稳定性",
"Inspection Department": "检验部门", "Painting Requirements": "喷漆要求",
"Performance\nObjective": "性能目标", "PERFORMANCE OBJECTIVE": "性能目标",
"PHYSICAL REQUIREMENTS": "物理性能要求", "Production Department": "生产部门",
"RAW MATERIAL FCA CODE": "原材料 FCA 代码", "Test Name & Procedure": "测试名称与方法",
"Voice of the Customer": "客户之声(VOC)", "Aesthetic Requirements": "外观要求",
"Cold Slam Requirements": "低温摔门要求", "Colorfastness to water": "耐水色牢度",
"Component Level Tests:": "零件级测试:", "Digital Model Assembly": "数字样机装配",
"Mechanical Information": "机械信息", "Must meet the standard": "须满足标准",
"Resistance to Crocking": "耐摩擦色牢度", "Appearance Requirements": "外观要求",
"Cold Impact Requirement": "低温冲击要求", "MECHANICAL REQUIREMENTS": "机械性能要求",
"Mechanical Requirements": "机械性能要求", "TEST NAME AND PROCEDURE": "测试名称与方法",
"Define tooling timelines": "确定模具时间计划", "Dimensional Requirements": "尺寸要求",
"PART INSPECTION STANDARD": "零件检验标准", "Project Plan Information": "项目计划信息",
"Strap Long Term Set Test": "绑带长期永久变形测试", "SYSTEM: BODY  - EXTERIOR": "系统:车身-外饰",
"COMPREHENSIVE PART LAYOUT": "全尺寸零件检测布局(CPL)", "Homologation requirements": "法规认证要求",
"Sum design responsibility": "设计责任合计", "Computer Aided Engineering": "计算机辅助工程(CAE)",
"ENVIRONMENTAL REQUIREMENTS": "环境性能要求", "Satisfy Door Slam Durability": "满足摔门耐久",
"Atmospheric Aging Requirement": "大气老化要求", "Glue on car body Requirements": "车身粘接要求",
"Number of Full Time Engineers": "全职工程师人数", "Product Development Milestone": "产品开发里程碑",
"Conduct vehicle system testing": "进行整车系统测试", "CS-9003 Recycling Requirements": "CS-9003 回收要求",
"Must meet standard requirement": "须满足标准要求", "MY & PROGRAM: Mirror protector": "年款与项目:镜面保护罩",
"Natural Weathering Requirement": "自然候化要求", "SURFACE AND TEXTURE EVALUATION": "表面与纹理评估",
"Chemical Resistance Requirement": "耐化学性要求", "Coating on mechanical fasteners": "机械紧固件镀层",
"Part Identification and Marking": "零件标识与打标", "Responsible for DV testing cost": "负责 DV 测试费用",
"COMPONENT PART NUMBER (SUPPLIER)": "零件号(供应商)", "Error proof \"supplied component\"": "对供货件做防错",
"Strap Attachment Strength Test –": "绑带连接强度测试 –", "Structural loading of bag handle": "袋提手结构承载",
"Design Verification Plan & Report": "设计验证计划与报告(DVP&R)",
"Flexible Strap Storage Cycle Test": "柔性绑带存放循环测试", "Heat Age\n(test specimen required)": "热老化(需测试样件)",
"Satisfy Door Vibration Durability": "满足车门振动耐久", "Support program tracking meetings": "支持项目跟踪会议",
"To record if there are any issues": "记录是否存在问题", "Door Trim Slam  Test  Requirements": "门饰摔门测试要求",
"Material Qualification - MS-JP-1-3": "材料认证 - MS-JP-1-3", "RELEASE ENGINEER: Francis Kingsley": "发布工程师:Francis Kingsley",
"Aerodynamic Requirements - Pressure": "空气动力学要求-压力", "Define vehicle build specifications": "定义整车制造规范",
"DESIGN VERIFICATION PLAN AND REPORT": "设计验证计划与报告(DVP&R)", "Maintain system DVP&R documentation": "维护系统 DVP&R 文档",
"Fatigue and Misuse Slam Requirements": "疲劳与误用摔门要求", "Glue Plastic on Plastic Requirements": "塑料-塑料粘接要求",
"Identify customer requirements (VOC)": "识别客户需求(VOC)", "Part Maintains Appearance / Function": "零件保持外观/功能",
"Resolve all system DMA interferences": "解决所有系统数字样机(DMA)干涉", "Aerodynamic Requirements - Wind Noise": "空气动力学要求-风噪",
"Door Trim Vibration Test  Requirements": "门饰振动测试要求", "Material and Finish/Surface Treatments": "材料与表面处理",
"Performance of part in thermal loading": "零件热负荷下的性能", "Design \"supplied component\" for the FDV": "为骡车(FDV)设计供货件",
"To test the durability of the Cargo net": "测试货网耐久性", "Conduct \"supplied component\" lab DV test": "进行供货件实验室 DV 测试",
"Process Failure Mode and Effect Analysis": "过程失效模式与影响分析(PFMEA)", "Identify part commonization opportunities": "识别零件通用化机会",
"Select all \"supplied component\" materials": "选定所有供货件材料", "Determine tooling facility &/or part source": "确定模具厂及/或零件来源",
"Review and report on assembly plant defects": "评审并报告装配厂缺陷", "To evaluate material specific Qualification": "评估材料专项认证",
"Conduct vehicle \"supplied component\" DV test": "进行整车供货件 DV 测试", "To check that part meet its build objectives": "检查零件是否达成制造目标",
"Provide Pre-VP part dimensional certification": "提供 Pre-VP 件尺寸认证", "Resolve Vehicle integration DMA interferences": "解决整车集成数字样机干涉",
"Participate in customer clinics / focus groups": "参与客户调研/焦点小组", "Develop a quality plan to meet quality objectives": "编制质量计划以达成质量目标",
"Maintain \"supplied component\" DVP&R documentation": "维护供货件 DVP&R 文档", "To evaluate color durability of interior material": "评估内饰材料颜色耐久",
"Establish \"supplied component\" DVP&R documentation": "建立供货件 DVP&R 文档", "Provide \"supplied component\" simulation/prototypes": "提供供货件仿真/样件",
"Resolve all \"supplied component\" DMA interferences": "解决所有供货件数字样机干涉", "Define serviceability of assembly and subcomponents": "定义总成及子件的可维修性",
"Design production intent check fixtures &/or gauges": "设计量产意图检具/量规", "Procure any required interfacing parts for DV testing": "采购 DV 测试所需的配合件",
"Maintain Appearance / Function": "保持外观/功能", "No wear through of material.": "材料不得磨穿。",
"Develop \"supplied component\" DFMEA": "编制供货件 DFMEA", "Develop \"supplied component\" PFMEA": "编制供货件 PFMEA",
"Must conform to CS-11000 & PS-4480": "须符合 CS-11000 与 PS-4480",
# —— 长条款 / 要求句 ——
"Engineering Statement of Work  (for CNs and Source Packages)": "工程工作说明书(用于变更通知CN与采购包)",
"Supplier Statement of Work  (for CNs and Source Packages)": "供应商工作说明书(用于变更通知CN与采购包)",
"Define quality targets (e.g. JD Powers, Consumer report, etc…)": "定义质量目标(如 J.D.Power、消费者报告等)",
"Establish supplier timeline to support program milestones": "建立供应商时间表以支持项目里程碑",
"Provide detail drawings of all serviceable components as defined by Service Parts Analysis": "按服务件分析要求,提供所有可维修件的详细图纸",
"Perform \"supplied component\" dimensional and functional test": "对供货件做尺寸与功能测试",
"Design \"supplied component\" tool (prototype &/or production)": "设计供货件模具(样件模及/或量产模)",
"Perform DV testing of Pre-VP parts (includes impact parts)": "对 Pre-VP 件做 DV 测试(含碰撞件)",
"Provide detail \"supplied component\" drawings, including structured serviceable sub-components": "提供供货件详细图纸,含结构化可维修子件",
"Submit all structured bills of material for assemblies to Service Parts Analysis": "向服务件分析提交所有总成的结构化 BOM",
"Provide \"supplied component\" simulation/prototypes": "提供供货件仿真/样件",
"Develop PFMEA, control plans, and assembly process for \"supplied component\"": "为供货件编制 PFMEA、控制计划及装配工艺",
"Perform CAE Analysis (Finite Element Analysis,...) for \"supplied component\"": "对供货件做 CAE 分析(有限元分析等)",
"Ensure material compatibility with interfacing parts & environment": "确保材料与配合件及环境的相容性",
"Ensure product integrity within the package constraints of the system/Vehicle": "在系统/整车的布置约束内确保产品完整性",
"Define functional objectives (Vehicle/System/supplied component Levels)": "定义功能目标(整车/系统/供货件层级)",
"Define functional objectives (Vehicle/System/\"supplied component\" Levels)": "定义功能目标(整车/系统/供货件层级)",
"Develop quality improvement proposals for review with FCA US Engineering": "编制质量改进提案,与 FCA US 工程评审",
"Provide sub-suppliers quality plan and documentation": "提供二级供应商质量计划及文档",
"Coordinate program tracking meetings": "组织项目跟踪会议", "Support program tracking meetings": "支持项目跟踪会议",
"Conduct vehicle system testing": "进行整车系统测试", "Maintain system DVP&R documentation": "维护系统 DVP&R 文档",
"Establish system DVP&R documentation": "建立系统 DVP&R 文档",
"Establish and maintain vehicle level DVP&R documentation": "建立并维护整车级 DVP&R 文档",
"Resolve all \"supplied component\" DMA interferences": "解决所有供货件数字样机干涉",
"Provide cost, weight & investements (CWI) revision for program direction changes (CN).": "针对项目方向变更(CN)提供成本、重量、投资(CWI)修订。",
"Compliant with Substance of Concern requirements (SoC) as per CS-11991": "符合 CS-11991 关注物质(SoC)要求",
"Complete the Supplier Design Acceptance Process/Checklist which includes the applicable portions at Step 2, Step 3, and Step 5.": "完成供应商设计接受流程/检查表(含第2、3、5步的适用部分)。",
"Identify customer requirements (VOC)": "识别客户需求(VOC)",
"Perform a weight optimization study to ensure that the supplier's product is the lightest possible design that meets or exceeds all functional and performance objectives.": "做轻量化研究,确保产品在满足/超越所有功能与性能目标前提下重量最轻。",
"Submit documentation showing that the weight optimization study has been completed, clearly identifying weight savings amount and graphically showing weight savings locations as compared to one or more relevant best-in-class reference designs.": "提交轻量化研究完成证明,明确减重量并以图示标出减重位置,与一个或多个同类最佳基准设计对比。",
"In case where advanced light weight materials are used, a weight optimization study is still required to identify even further weight savings.": "即使采用先进轻量化材料,仍需做轻量化研究以挖掘进一步减重空间。",
"Demonstrate that the optimized design meets all system level requirements, engineering measures and targets prior to design release.": "在设计发布前,证明优化设计满足所有系统级要求、工程指标与目标。",
"Define vehicle build specifications": "定义整车制造规范",
# —— DVP 测试要求/判定 ——
"Must meet hardness requirements.": "须满足硬度要求。",
"Max 10% change after heat age": "热老化后变化≤10%",
"No cracking, breaking, or shattering.": "无开裂、断裂或碎裂。",
"Report dimensional changes (in %) in both directions.": "报告两个方向的尺寸变化(%)。",
"There shall be no noticable degradation, separating, or other detrimental change to material": "材料不得有明显劣化、分离或其它有害变化",
"Material shall not display surface irregularities, gloss change, odor, color, or objectionable observations after exposure to tests.": "测试后材料不得出现表面不平、光泽变化、异味、变色或其它不良现象。",
"No disagreeable odor either wet or dry at any temperature up to 85°C.": "在不超过85°C的任何温度下,干或湿状态均无异味。",
"No fractures and must withstand the load without any yield": "无断裂,且承载下不得屈服",
"Bag/handle must withstand content loads of 10lbs": "袋/提手须承受10磅内容物负载",
"Part shall not yield, crack, show any kind of stress or experience any kind loss of retention from thermal loading": "零件在热负荷下不得屈服、开裂、出现应力或任何固定失效",
"No noticeable ringing, color change,  or other detrimental effects.": "无明显异响、变色或其它有害影响。",
"No changes in appearance or other detrimental changes.": "外观无变化,也无其它有害变化。",
"Formation of crystals and/or droplets is reason for rejection.": "出现结晶和/或液滴即判不合格。",
"No florescense, blooming, exudation, tackiness, and/or changes in color.": "无析出、泛白、渗出、发粘和/或变色。",
"Maintain Appearance": "保持外观", "Stay Retained": "保持固定不脱落",
"Load Normal to the Door Panel Surface PF.90058 Section 7.38.1": "垂直于门板表面加载,PF.90058 第7.38.1节",
"Load Vertical to the Door Panel Surface PF.90058 Section 7.38.2": "门板表面法向加载,PF.90058 第7.38.2节",
"At completion of test, components must meet all criteria outlined in MS-JP-9-5 SEC. 3.1.3 (SAE J2527), Xenon Arc Weathering": "测试完成后,零件须满足 MS-JP-9-5 第3.1.3节(SAE J2527 氙弧候化)的全部判据",
"Resistance to Heat Aging (7 days at 85°C )": "耐热老化(85°C 7天)",
"100 hrs at 95-100% RH @ 38°C": "38°C、95-100%相对湿度下100小时",
"7 days @ 85°C": "85°C 7天", "112.8 kJ/m²": "112.8 kJ/m²",
"No wear through of material.": "材料不得磨穿。",
"Must meet the standard": "须满足标准", "Must meet the general guidelines of the standard": "须满足该标准的总体要求",
"Must comply": "须符合", "Shall comply": "须符合", "Compl": "完成",
"Results must be submitted and approved by engineer and materials engineer": "结果须提交并经工程师与材料工程师批准",
"Completed Compliance Report Form must be included with test results.": "测试结果须附完整的合规报告表。",
"State quantifiable test results based on specified Acceptance Criteria & Test Target.": "依据规定的合格判据与测试目标,给出可量化的测试结果。",
"The quantifiable/measurable statement that is to be verified through testing, evaluation, etc.": "通过测试、评估等加以验证的可量化/可测量的陈述。",
"Test Name & Procedure": "测试名称与方法",
"Specific test title and applicable reference procedure or standard. If needed provide a brief/concise description.": "具体测试名称及适用的参考方法或标准;必要时给出简要说明。",
"Acceptance Criteria/\nTest Target": "合格判据/测试目标",
"Acceptance Criteria\nThe quantifiable time or performance value that each test sample must achieve (i.e. < 22cc/m @ 5psi).": "合格判据:每个样件须达到的可量化时间或性能值(如 <22cc/m @5psi)。",
"Test Target\nSpecific statement regarding test requirements (i.e. R90/C90, R90C70, P90/C90, P99/C90, No Failures per requirements, etc.).": "测试目标:关于测试要求的具体陈述(如 R90/C90、P90/C90、按要求无失效等)。",
# —— RACI / RR-ADP 职责文件 ——
"ROLES & RESPONSIBILITIES DOCUMENT": "角色与职责文件(RR)",
"AUTHORITY DEFINITION PLAN (ADP) DOCUMENT": "权责界定计划(ADP)文件",
"Roles & Responsibilities (RR) Document Instructions": "角色与职责(RR)文件说明",
"Roles & Responsibilies Document Acronym Descriptions": "角色与职责文件 缩写说明",
"General Instruction For Use of This Document": "本文件使用总说明",
"Task and Functions": "任务与职能",
"\"Supplied Component\" & / or Commodity (CORE Functions)": "“供货件”及/或品类(核心职能)",
"\"Supplied Component\" refers to the part number (s) being quoted by the individual supplier.": "“供货件”指各供应商所报价的零件号。",
"\"System\" referes to any vehicle system that uses the \"supplied component\".": "“系统”指使用该供货件的任何整车系统。",
"\"System\" referes to any vehicle system that uses the supplied \"supplied component\".": "“系统”指使用该供货件的任何整车系统。",
"A (Acceptance) -->  Acceptance to proceed but does not own the task / project.  Assign \"A\" only when needed (not required for every task).": "A(认可)→ 同意推进但不拥有该任务/项目;仅在需要时指派A(并非每项任务都需要)。",
"R (Responsible) -->  Owns the task / project and is accountable for the result.  Should not proceed without Acceptance from the other party when \"A\" is assigned.  There cannot be more than one \"R\" per task.": "R(负责)→ 拥有该任务/项目并对结果负责;若指派了A,须经对方认可方可推进;每项任务只能有一个R。",
"NA (Non-Applicable) --> If a task is non-applicable to the \"Supplied Component\", then leave blank and place 'NA' in the comments column.": "NA(不适用)→ 若某任务对供货件不适用,则留空并在备注列填'NA'。",
"Only one 'R' (Responsible) per task.  There can only be one owner of a task.": "每项任务只能有一个'R'(负责);任务只能有一个责任人。",
"A' (Acceptance) is only required when either the Supplier or FCA US need to review the outcome of the task.": "仅当供应商或 FCA US 需要评审任务结果时才需要'A'(认可)。",
"ADP tasks must have 'R' responsibility defined.  Do not put 'NA' for these tasks.": "ADP 任务必须定义'R'责任,不得填'NA'。",
"If a task is non applicable to your component, then leave blank and add 'NA' in the comments column.": "若任务对你的零件不适用,留空并在备注列填'NA'。",
"Multiple commodities can point to the same RR/ADP document.": "多个品类可指向同一份 RR/ADP 文件。",
"Each sourced commodity requires a Roles & Responsibilities, RR and ADP document to be stored in ADRESS.": "每个定点品类都需在 ADRESS 系统中存有 RR 与 ADP 文件。",
"This document is to define Roles and Responsibilities for the purpose of providing quotations by suppliers for a given commodity": "本文件用于界定某品类供应商报价时的角色与职责",
"This document is to define the Roles and Responsibilities for the purpose of": "本文件用于界定角色与职责,目的是",
"providing quotations by Suppliers for a given commodity.": "供应商对某品类进行报价。",
"This document is not intended to act as an engineering checklist for every task to be": "本文件并非用作每项任务的工程检查表,",
"accomplished for a given program.": "(以完成某个项目)。",
"This document is to assist in the determination of financial responsibility for warranty expense for a given commodity": "本文件用于协助界定某品类保修费用的财务责任",
"These fields on this page are all auto generated from the RR Template": "本页字段均由 RR 模板自动生成",
"The ADP document does not require any manual input from the engineer.  It is autogenerated based on inputs": "ADP 文件无需工程师手动输入,基于输入自动生成",
"within the RR document.": "(在 RR 文件中)。",
"Once complete, the document requires approval by the commodity Supervisor and Sr. Manager through ADRESS.": "完成后,文件须经品类主管与高级经理通过 ADRESS 审批。",
"Use the second page of RR template to add any additional cost driven tasks for a particular commodity.": "用 RR 模板第二页为特定品类补充其它成本相关任务。",
"NOTE: Add any other tasks and functions that will impact supplier quotation for the given commodity": "注:补充会影响该品类供应商报价的其它任务与职能",
"Sum design responsibility": "设计责任合计",
"Percent responsible if warranty is design related": "保修为设计相关时的责任比例",
"Percent responsible if warranty is Supplier process related": "保修为供应商过程相关时的责任比例",
"Percent responsible if warranty is FCA US process related": "保修为 FCA US 过程相关时的责任比例",
"See ACRONYM Tab for list of acronym descriptions": "缩写释义见 ACRONYM 页",
"Advanced Product Quality Planning": "先期产品质量策划(APQP)",
"Computer Aided Engineering": "计算机辅助工程(CAE)", "Change Notice": "变更通知(CN)",
"Design Failure Mode and Effect Analysis": "设计失效模式与影响分析(DFMEA)",
"Process Failure Mode and Effect Analysis": "过程失效模式与影响分析(PFMEA)",
"Digital Model Assembly": "数字样机装配(DMA)", "Design Verification": "设计验证(DV)",
"Functional Development Vehicle (mule vehicle)": "功能开发车(骡车)",
"Voice of the Customer": "客户之声(VOC)", "House of Quality": "质量屋(HoQ)",
"Design Verification Plan & Report": "设计验证计划与报告(DVP&R)",
# —— ATAR 外观批准表 ——
"APPEARANCE TECHNICAL APPROVAL REPORT    1/2": "外观技术批准报告(ATAR) 第1/2页",
"APPEARANCE TECHNICAL APPROVAL REPORT    2/2": "外观技术批准报告(ATAR) 第2/2页",
"FCA END ITEM NUMBER (CODEP/EBOM)": "FCA 成品件号(CODEP/EBOM)",
"SUPPLIER NAME & CODE (TIER 1)": "供应商名称及代码(一级)",
"SUPPLIER NAME1\n(TIER 2)": "供应商名称(二级)", "MANUFACTURING SUPPLIER LOCATION": "制造供应商地点",
"RELEASE ENGINEER /\nPROJECT CHIEF": "发布工程师/项目主管", "MODEL YEAR": "年款", "VEHICLE CODE(S)": "车型代码",
"SURFACE AND TEXTURE EVALUATION": "表面与纹理评估", "MATERIAL, COLOR, AND GLOSS EVALUATION": "材料、颜色与光泽评估",
"ORNAMENTATION AND GRAPHICS REQUIREMENT": "装饰与图案要求", "COLOR AND GLOSS SUBMIT PART DATA": "颜色与光泽 提交零件数据",
"PRE-TEXTURE SURFACE APPROVAL": "晒纹前 表面批准", "POST-TEXTURE SURFACE APPROVAL (if conditional only)": "晒纹后 表面批准(仅限有条件时)",
"ENGINEERING  APPROVAL A-Surface\n(DIMENSIONAL OK FOR PRE-TEXTURE)": "A面工程批准(尺寸合格,可晒纹)",
"SUPPLIER APPROVAL SIGNATURE": "供应商批准签字", "FINAL APPROVAL SIGNATURE & TID": "最终批准签字与 TID",
"INTERIM APPROVAL SIGNATURE & TID": "中期批准签字与 TID", "FCA SIGNATURE & TID WITH DATE": "FCA 签字、TID 及日期",
"FCA APPROVAL SIGNATURE & TID": "FCA 批准签字与 TID",
"FCA MAT’L OR PAINT SPEC. & CPN # / CODE": "FCA 材料或油漆规格 及 CPN号/代码",
# —— 样件类型图例 ——
"Sample Type": "样件类型", "Sample Type:   ": "样件类型:",
"PHM = Prototype-hand made": "PHM=手工样件", "PT = Prototype-tooled": "PT=工装样件",
"S1 = Prod. Design Intent": "S1=量产设计意图件", "S2 = Prod. Process": "S2=量产过程件",
"VP = Volume Production": "VP=批量生产", "PHM = Prototype-hand made.": "PHM=手工样件。",
"PT = Prototype-tooled.": "PT=工装样件。", "Pre-VP = Pre-Verification of Process.": "Pre-VP=过程预验证。",
"VP = Verification of Process.": "VP=过程验证。", "CAE - Virtual Analysis": "CAE-虚拟分析",
"PVP = Pre Volume Production.      Job 1 Offline.": "PVP=量产前生产;量产首件下线(Job1)。",
# —— 粘接/打标技术要求 ——
"TECHNICAL SPECIFICATION REQUIREMENTS FOR THE BONDING OF PLASTIC PARTS": "塑料件粘接技术规范要求",
"Gluing between two plastic parts (for example, between aesthetical skin and its reinforcement) must meet the following requirements:": "两塑料件之间的粘接(例如外观表皮与其加强件)须满足以下要求:",
"- Initial resistance to shear stress: > 1.8 MPa": "- 初始抗剪强度:>1.8 MPa",
"- Resistance to shear stress after 500 h @90°C: > 1.5 MPa": "- 90°C 500小时后抗剪强度:>1.5 MPa",
"- Resistance to shear stress after 500 h in CTUS: > 1.5 MPa": "- CTUS 500小时后抗剪强度:>1.5 MPa",
"- Resistance to shear stress after 3 thermal cycling: > 1.5 MPa": "- 3次热循环后抗剪强度:>1.5 MPa",
"Following items to be on the label:": "标签上须包含以下信息:",
"B - FCA US Part Number": "B - FCA US 零件号", "E - Date of Manufacture - Daily": "E - 制造日期(按日)",
"K - Change Level": "K - 更改级别", "Plant approved bar code": "工厂认可的条形码",
"Build Objective Requirements": "制造目标要求",
"Dimensional Requirements as specified on the GD&T.": "按 GD&T 规定的尺寸要求。",
"Note": "备注", "Report": "报告",
# —— 批次5: DVP 测试名 / 判据 / 表单字段 / 要求句 ——
"Acronym": "缩写", "INITIAL": "初始", "Marking": "标识/打标", "type of": "类型",
"AVG FTEs": "平均全职人力", "CATEGORY": "类别", "CATEGORY:": "类别:", "COMMENTS:": "备注:",
"SCAN/CMM": "扫描/三坐标(CMM)", "SEE GD&T": "见 GD&T", "Name / NIC": "姓名/工号(NIC)",
"COLOR\nCURVE": "颜色曲线", "PF Sect.  #": "PF 章节号", "- CAD Design": "- CAD 设计",
"Avg hrs a wk": "每周平均工时", "DVPR NUMBER:": "DVP&R 编号:", "ED/FEA\nDV\nPV": "ED/FEA、DV、PV",
"Ecmm UPLOAD?": "是否上传 eCMM?", "FCA COMMENTS": "FCA 备注", "GLOSS (UNit)": "光泽(单位)",
"J1 + 90 DAYS": "量产首件(J1)后90天", "MEAS. METHOD": "测量方法", "PART NUMBER:": "件号:",
"REVISION: 01": "版本:01", "Sample Type:": "样件类型:", "Sweden steel": "瑞典钢",
"TEST RESULTS": "测试结果", "Test Results": "测试结果", "if available": "如有",
"SOFTNESS (mm)": "软度(mm)", "Wet and Dry": "干与湿", "VEHICLE": "车型", "MY / FAMILY:": "年款/平台:",
"ENGINEERING COMMENTS1": "工程备注", "Maximum of 100mm/min.": "最大 100mm/分钟。",
"SUPPLIER CONTACT: TBD": "供应商联系人:待定", "System Level  Tests:": "系统级测试:",
"Vehicle Level  Tests:": "整车级测试:", "- Software Engineering": "- 软件工程",
"- Program Management": "- 项目管理", "PER PQP QUALITY LOOP": "按 PQP 质量循环",
"SOURCE PACKAGE NUMBER:": "采购包编号:", "Part Numbers --------->": "零件号 --------->",
"Weekly Grand Total$": "周总计($)", "Weekly Total Labor$": "周人工合计($)",
"Weekly Total Non Labor$": "周非人工合计($)", "Source(s) / Supplier(s):": "来源/供应商:",
"Minimum of 4 AATCC scale.": "AATCC 灰卡≥4级。", "SPECIFICATION / TOLERANCE": "规格/公差",
"SXV durability run at CPG": "在 CPG 做 SXV 耐久试验", "Theme Confirmation Step B": "造型确认 B 步",
"Contact/Phone Number:  TBD": "联系人/电话:待定", "PER ENHANCED  CONTROL PLAN": "按强化控制计划",
"4 No Variable Data Required": "4=无需计量数据", "Approved by (FCA US Buyer):": "批准(FCA US 采购员):",
"Reviewed by (ED&D Analyst):": "评审(ED&D 分析师):", "- Homologation Certification": "- 法规认证",
"ATTRIBUTE CHECKS PER CONTROL": "按控制计划做属性检查", "As specified for application": "按应用规定",
"3 samples": "3 件样件", "MIN FREQ. (PER VALUE STREAM)": "最小频次(每价值流)",
"7 days @ 85°C": "85°C 7天", "Document Number:  RR-Template": "文件编号:RR-Template",
"Software test plan --------->": "软件测试计划 --------->", "Deliverable(s) being worked on": "正在进行的交付物",
"Development site(s) --------->": "开发地点 --------->", "Equivalent Heads (by ED&D Role)": "折合人头(按 ED&D 角色)",
"IMDS Data entered into Database": "IMDS 数据已录入数据库", "Is the part production sourced?": "零件是否已量产定点?",
"CRITICAL POINTS\n (PER CEP-12679)": "关键点(按 CEP-12679)", "Automatic Car Wash Pull Away Test": "自动洗车拉脱测试",
"CHARACTERISTIC / INSPECTION POINT": "特性/检验点", "Check inspection or No inspection": "抽检或免检",
"Crocking\n(test specimen required)": "摩擦色牢度(需测试样件)", "MUST INCLUDE ALL FEATURES OF SIZE": "须包含所有尺寸特征",
"Model Year & Vehicle (ie 2012 WD)": "年款与车型(如 2012 WD)", "See DFMEA, DVP&R, and attachments": "见 DFMEA、DVP&R 及附件",
"- Design Validation (testing only)": "- 设计验证(仅测试)", "Purpose of ED&D request --------->": "ED&D 申请目的 --------->",
"Supplier to Complete (Labor Costs)": "由供应商填写(人工费)", "6 Months After Original Launch Date": "原投产日期后6个月",
"Approved by System Responsible (SR)": "由系统责任人(SR)批准", "COMPONENT PARTS - GD&T REQUIREMENTS": "零件 GD&T 要求",
"See Deliverables in Engineering SOW": "见工程 SOW 中的交付物", "DV test plan - Electrical --------->": "DV 测试计划-电气 --------->",
"DV test plan - Mechanical --------->": "DV 测试计划-机械 --------->", "Description of Work to be Completed:": "待完成工作描述:",
"Resistance to Fade Xenon-225.6 kJ/m2": "氙灯耐褪色 225.6 kJ/m²", "Supplier to Complete (DV Test Costs)": "由供应商填写(DV 测试费)",
"ACCEPTANCE CRITERIA: WITHIN TOLERANCE": "合格判据:在公差内", "Cleanability\n(test specimen required)": "易清洁性(需测试样件)",
"3 Minimal Risk to Function or Geometry": "3=对功能或几何风险极小", "Component:2025 EJ Door Elastic Storage": "零件:2025 EJ 车门弹性储物",
"Sampling inspection or Check inspection": "抽样检验或抽检", "Vehicle Program & Model Year --------->": "车型项目与年款 --------->",
"ED&D Engineer to Complete the following:": "ED&D 工程师填写以下:", "Part Indentification:  PS-4480, CS-11000": "零件标识:PS-4480、CS-11000",
"TORQUE TIGHTNESS - METRIC THREADED PARTS": "拧紧扭矩-公制螺纹件", "• SEE QR-10012 FOR FURTHER REQUIREMENTS.": "• 进一步要求见 QR-10012。",
"FCA US LLC Commodity Manager (Purchasing)": "FCA US 品类经理(采购)", "Fogging, photometric\n(fog plate requried)": "雾化(光度法,需雾化板)",
"Xenon Resistance\n(test specimen required)": "氙灯老化(需测试样件)", "100 hrs at 95-100% RH @ 38°C": "38°C、95-100%RH 下100小时",
"Basic / Recurring Supplier Costs, such as:": "基础/经常性供应商成本,例如:", "FCA US Engineer to Complete the following:": "FCA US 工程师填写以下:",
"Additional Material Color Durability Tests:": "附加材料颜色耐久测试:", "Approved & Funding Verified by (FCA US SR):": "批准并核实经费(FCA US SR):",
"Design Verification Plan And Report (DVP&R)": "设计验证计划与报告(DVP&R)", "Hardware Validation requirements --------->": "硬件验证要求 --------->",
"Purpose of this ED&D requisition --------->": "本 ED&D 申请目的 --------->", "Soiling Resistance\n(test specimen required)": "耐沾污性(需测试样件)",
"Supplier to Complete (Design Mock Up Costs)": "由供应商填写(设计样模费)", "Theme Confirmation Step C/ Program Approval": "造型确认 C 步/项目批准",
"High-level description of project --------->": "项目概要描述 --------->", "- Product Validation (PV) Testing / Reporting": "- 产品验证(PV)测试/报告",
"Grease & General Cleanability": "耐油脂与一般易清洁性", "Mechanical Validation Requirements --------->": "机械验证要求 --------->",
"TAG PRE-TEXTURE APPROVAL1\n(OK TO TEXTURE TOOL)": "晒纹前批准(模具可晒纹)", "- Product Engineering (hardware and mechanical)": "- 产品工程(硬件与机械)",
"Taber Wear Resistance \n(test specimen required)": "Taber 耐磨(需测试样件)", "Third party SOW and associated quote --------->": "第三方 SOW 及相关报价 --------->",
"after 6 hours heat age per line 1.1.7": "按 1.1.7 行做6小时热老化后", "High Level description of the project --------->": "项目概要描述 --------->",
"Over tightning test carried out at supplier end.": "过拧测试在供应商端进行。", "2 Dimensionally Significant - Geometry/Part Fitup": "2=尺寸重要-几何/零件配合",
"COATING SYSTEM - BLACK, GALVANIC PROTECTION BASED": "涂层体系-黑色,电镀防护型", "Completes all of the blue colored worksheets/tabs.": "完成所有蓝色工作表/页签。",
"ED&D Engineer (Analyst) to Complete the following:": "ED&D 工程师(分析师)填写以下:", "Supplier ED&D Price Break Down Template - ED&D PBD": "供应商 ED&D 费用分解模板(ED&D PBD)",
"Third Party Suppliers, Roles, Locations --------->": "第三方供应商、角色、地点 --------->", "IMDS Data available in IMDS before part is released": "零件发布前 IMDS 数据须在 IMDS 系统中可查",
"Scratch and Mar Resistance\n(test specimen required)": "耐划伤与耐擦伤(需测试样件)", "System & Vehicle Validation Requirements --------->": "系统与整车验证要求 --------->",
"Salt Solution Immersion (3%)\n(test specimen required)": "盐水浸泡(3%)(需测试样件)", "Scratch Resistance Requirements for grained components": "晒纹件耐划伤要求",
"Provide brief comparison to existing product---------->": "提供与现有产品的简要对比 --------->", "DIMENSIONAL VERIFICATION SCAN OR LONG PROGRAM\n(SD-12690)": "尺寸验证扫描或长程序(SD-12690)",
"Part Description (& Part Numbers if available)--------->": "零件描述(及零件号,如有) --------->", "Cold Flexability (Cold Cracking)\n(test specimen required)": "低温柔韧性(低温开裂)(需测试样件)",
"Cold Impact Test. Large object Option (pendulum).\nLP.7N022": "低温冲击测试-大物体(摆锤),LP.7N022", "Maximum scratch severity rating of 3 using a 7mm dia. Pin.": "用7mm直径针,最大划伤等级3。",
"Resistance to Condensing Humidity\n(test specimen required)": "耐凝露湿热(需测试样件)", "Cold Impact Test. Small object Option (ball drop).\nLP.7N022": "低温冲击测试-小物体(落球),LP.7N022",
"Durability of plastics for Exterior Components per MS-JP9-8": "外饰塑料件耐久(按 MS-JP9-8)", "The following is considered valid for advance ED&D Payment:": "以下情形可作为 ED&D 预付款的有效依据:",
"APPEARANCE / PHYSICAL / MECHANICAL / ELECTRICAL REQUIREMENTS": "外观/物理/机械/电气要求", "Completes the Engineering SOW worksheet/tab (colored orange)": "完成工程 SOW 工作表(橙色页签)",
"Supplier to Complete (Labor Costs) - Do not modify this form": "由供应商填写(人工费)-请勿修改此表", "1 Dimensionally Significant - Fit/Finish/Suspension Alignment": "1=尺寸重要-配合/外观/悬架对中",
"Section 4.3 (LP.7M052) - Automotive Fluid Resistance": "第4.3节(LP.7M052)-耐汽车油液", "Resistance to efflorescence/exudation\n(test specimen required)": "耐析白/渗出(需测试样件)",
"Procedure 1-soil (100 cycles), Procedure 2-clean": "程序1-沾污(100次),程序2-清洁", "The following is NOT considered valid for advance ED&D Payment:": "以下情形不可作为 ED&D 预付款依据:",
"Resistance to Humidity/Hot/Cold Cycling\n(test specimen required)": "耐湿热/冷热循环(需测试样件)", "PRE-TEXTURE MAPPING APPROVAL (TGSS)": "晒纹前纹理映射批准(TGSS)",
"Max deflection allowed in each test zone as per LP.7N025 - Zone A": "各测试区允许最大挠度,按 LP.7N025-A区", "ORNAMENTATION, GRAPHICS, SURFACE TACTILITY AND SPECIAL PROPERTIES1": "装饰、图案、表面触感及特殊性能",
"As received and after heat aging per line 1.1.7": "收货态及按1.1.7行热老化后", "- Process Sign-off (PSO) and Production Part Approval Process (PPAP)": "- 工艺签核(PSO)与生产件批准(PPAP)",
"Support all packaging and feasibility studies (on site if necessary)": "支持所有包装与可行性研究(必要时到现场)", "Enter here the acceptance transaction number for/by each part number.": "在此填写每个零件号的验收交易号。",
"- Corrections to Supplier Design Errors (actions not driven by FCA US)": "- 供应商设计错误的纠正(非 FCA US 驱动)", "Formation of crystals and/or droplets is reason for rejection.": "出现结晶和/或液滴即判不合格。",
"Chemical Resistance Requirements - Resistance test to H2SO4 acid agent": "耐化学要求-耐硫酸(H2SO4)测试", "Chemical Resistance Requirements - Contact resistance test with mineral oil": "耐化学要求-矿物油接触测试",
"Chemical Resistance Requirements - Contact resistance test to windshield washer fluid DP1": "耐化学要求-玻璃水(DP1)接触测试", "Fasteners Grade & surface treatment / coating details & reports not provided.": "未提供紧固件等级、表面处理/镀层细节及报告。",
"Minimum of 4 AATCC scale, also report Delta E, Delta H, Delta C, and L, a, b.": "AATCC 灰卡≥4级,并报告 ΔE、ΔH、ΔC 及 L、a、b。", "All fasteners / loose hardware shall be coated in full compliance with PS-12182": "所有紧固件/松散五金件须完全按 PS-12182 镀涂",
"Material Qualification:": "材料认证:", "Material Qualification - MS-JP-1-3": "材料认证-MS-JP-1-3",
"Buckle - MS.50042": "带扣 Buckle - MS.50042", "Color - MS-JP-1-3": "颜色 - MS-JP-1-3", "Cord - MS-JZ-12-20": "绳/绑带 - MS-JZ-12-20",
"To evaluate material specific Qualification": "评估材料专项认证", "To evaluate color durability of interior material": "评估内饰材料颜色耐久",
"Resistance to Heat Aging (7 days at 85°C )": "耐热老化(85°C 7天)", "Humidity 168h @ 100%RH": "100%RH 下168小时湿度",
"Humidity resistance per ASTM D1735-92, Determination of Condensing": "按 ASTM D1735-92 耐湿(凝露判定)",
"Deliverables --------->\nAttach NX Model & Approved DVP&R (Environmental & EMC)": "交付物 ---------> 附 NX 模型与已批准 DVP&R(环境与 EMC)",
"Deliverables --------->\nIncludes NX Model & Approved DVP&R (Environmental & EMC)": "交付物 ---------> 含 NX 模型与已批准 DVP&R(环境与 EMC)",
"Alpha (P/T)": "Alpha(样件)", "Beta (P/T)": "Beta(样件)", "Gamma (P/T)": "Gamma(样件)",
"Pre-Pilot (P/T)": "预试产(样件)", "Pilot (P/T)": "试产(样件)",
"There shall be no noticable degradation, separating, or other detrimental change to material": "材料不得有明显劣化、分离或其它有害变化",
"PART GEOMETRY SHOWN IS FOR REFERENCE AND MAY NOT REPRESENT LATEST PRODUCT DESIGN.": "所示零件几何仅供参考,可能不代表最新产品设计。",
"FCA US:": "FCA US:", "Hardware Information\n(This section only required for electronic components/systems)": "硬件信息(仅电子件/系统需填)",
"Software Information\n(This section only required for electronic components/systems)": "软件信息(仅电子件/系统需填)",
"Resistance to Crocking per Chrysler LP-463PB-54-01 (For High Gloss applications only)": "耐摩擦色牢度(按 LP-463PB-54-01,仅高光泽件)",
"Resistance to Crocking per Chrysler LP-463PB-54-01/02 (For High Gloss applications only)": "耐摩擦色牢度(按 LP-463PB-54-01/02,仅高光泽件)",
"Identify the key functions of the system in need of Robust Optimization (Function Map)": "识别系统中需稳健性优化的关键功能(功能图)",
"Completed the Engineer's \"Header Section\" (red boxes) within the ED&D PBD worksheet/tab": "已完成 ED&D PBD 表中工程师“表头部分”(红框)",
"• PART PRODUCER IS REQUIRED TO IMPLEMENT THESE REQUIREMENTS INTO PRODUCTION CONTROL PLAN": "• 零件生产方须将这些要求纳入量产控制计划",
"0.00013 (Date)": "0.00013(日期标准)", "07412 (Trademark)": "07412(商标标准)",
"07610 (Supplier Code)": "07610(供应商代码标准)", "07416 (Material recycling marking)": "07416(材料回收标识标准)",
"Identify the cost sensitivity of the factors effecting the selected functions’ robustness": "识别影响所选功能稳健性的各因素的成本敏感度",
"Software Validation Requirements--------->\n(Be sure to indicate Full or Partial Validation)": "软件验证要求 --------->(务必注明完整或部分验证)",
"5 PIECE ANNUAL CERTIFICATION REQUIRED.  DATA IS REQUIRED TO BE UPLOADED TO eCMM.": "需每年5件认证,数据须上传 eCMM。",
"- Prototype & DV parts & tooling, developmental / Pilot Parts (paid via separate requisition)": "- 样件、DV 件及模具、开发/试产件(单独申请付款)",
"Five Finger Scratch Test\nUse 1mm diameter scratch pin.\n4, 6, 8, 10 and 15N loads.": "五指划伤测试:用1mm直径划针,载荷 4/6/8/10/15N。",
"Note:  This quotation is subject to terms of a FCA US LLC purchase order and / or ED&D contract.": "注:本报价受 FCA US LLC 采购订单及/或 ED&D 合同条款约束。",
"State quantifiable test results based on specified Acceptance Criteria & Test Target.": "依据规定的合格判据与测试目标给出可量化结果。",
"Asphalt Staining Resistance (Not applicable for black or dark colored materials) per LP-463PB-57-02": "耐沥青沾污(按 LP-463PB-57-02,黑/深色材料不适用)",
"* Engineer and supplier to determine if required testing can be performed by FCA US Sci Labs (Yes/No)": "* 工程师与供应商确定所需测试是否可由 FCA US 科学实验室进行(是/否)",
"Minimum of 4 on AATCC Gray scale and a maximum of 3.0 Delta E. Report Delta H, Delta C, and L, a, b data.": "AATCC 灰卡≥4级、ΔE≤3.0;并报告 ΔH、ΔC 及 L、a、b 数据。",
"As received and after heat aging per line 1.1.7": "收货态及按1.1.7行热老化后", "2.54 cm (1.0in) diameter mandrel, -30°C": "2.54cm(1.0英寸)直径芯轴,-30°C",
"Describe any unique test sample characteristics, testing criteria, analysis techniques, test results, etc.": "描述样件的特殊特征、测试判据、分析方法、测试结果等。",
"• CRITICAL CHARACTERISTICS REQUIRE DEMONSTRATION OF PROCESS CAPABILITY AND ONGOING DATA COLLECTION PER CEP-12679.": "• 关键特性须按 CEP-12679 证明过程能力并持续采集数据。",
"Procedure 1 - Report results": "程序1-报告结果", "Procedure 2 - Minimum of 4 on AATCC Gray Scale for evaluating resistance to staining.": "程序2-耐沾污 AATCC 灰卡≥4级。",
"Performance Objective": "性能目标", "The quantifiable/measurable statement that is to be verified through testing, evaluation, etc.": "通过测试、评估等加以验证的可量化/可测量陈述。",
"In order for this ED&D requisition to be processed, the information required in this tab must be input by the Supplier.": "为处理本 ED&D 申请,本页所需信息须由供应商填写。",
"3) Above data is provided as example only and of course should be overwritten/deleted when using for an official request.": "3) 上述数据仅为示例,正式申请时应覆盖/删除。",
"After completing the Engineering SOW worksheet/tab, Engineer attaches this document to standard or \"What-If\" Source Package": "完成工程 SOW 工作表后,工程师将本文件附到标准或“What-If”采购包",
"Identify the relationship between the VOC & system level requirements and the functions necessary to achieve them (HoQ Phase 2)": "识别客户之声(VOC)与系统级要求及实现功能之间的关系(质量屋第2阶段)",
"In order for this ED&D requisition to be processed, the information required in this tab must be input by the requesting Engineer.": "为处理本 ED&D 申请,本页所需信息须由申请工程师填写。",
"The cladding must meet a minimum strength of 900 N (target as to be checked after test on component) for an impulsive upward load.": "护板对向上冲击载荷须满足最低900N强度(目标值需在零件测试后核实)。",
"Ensure no negative influences that could potentially act on the \"supplied component\" (e.g. temperature, humidity, UV, fluids, etc.)": "确保对供货件无潜在不利影响(如温度、湿度、UV、油液等)",
"Ensure no negative influences that could potentially act on the \"supplied component\" (e.g. temperature, humidity, UV, fluids, etc…)": "确保对供货件无潜在不利影响(如温度、湿度、UV、油液等)",
"Detailed description and task breakdown associated with each feature/function, including effort, duration, and resources. --------->": "各功能的详细描述与任务分解,含工作量、工期、资源 --------->",
"Wheel flares and claddings shall meet the material and surface treatment requirements specified in the Source Package and/or Drawing.": "轮眉与护板须满足采购包及/或图纸规定的材料与表面处理要求。",
"2) Additional columns or rows may be added to above as required to capture all ED&D activities.  Hourly Rate may be adjusted as needed.": "2) 可按需增列/行以涵盖所有 ED&D 活动;小时费率可按需调整。",
"Test Name & Procedure": "测试名称与方法", "Specific test title and applicable reference procedure or standard. If needed provide a brief/concise description.": "具体测试名称及适用参考方法或标准;必要时简要说明。",
"No noticeable ringing, color change,  or other detrimental effects.": "无明显异响、变色或其它有害影响。", "Minimum of 4 on AATCC Gray Scale for evaluating resistance to staining.": "耐沾污 AATCC 灰卡≥4级。",
"Identify the relationship between inputs and outputs (Ideal Function) that best represents the primary purpose of each key function selected": "识别最能代表各关键功能主要目的的输入输出关系(理想函数)",
"After receiving this spreadsheet back from the Supplier, the Buyer confirms that the Supplier has completed all of the blue colored worksheets/tabs.": "收到供应商回传后,采购员确认供应商已完成所有蓝色工作表/页签。",
"Identify factors and levels that can be controlled that may result in the highest or targeted level of performance with minimal effect on Robustness.": "识别可控因素及水平,在对稳健性影响最小的前提下获得最高/目标性能。",
"(If the maximum burn rate exceeds 90 mm/min or the average exceeds 85 mm/min, an additional 10 specimens in both directions must be burned.)": "(若最大燃烧速率>90mm/min 或平均>85mm/min,须在两个方向各加烧10件。)",
"Before this spreadsheet is forwarded to the Supplier, the Buyer confirms the Engineer has populated the Engineering SOW worksheet/tab (colored orange).": "转交供应商前,采购员确认工程师已填好工程 SOW 工作表(橙色)。",
"For vents with a hook and rotate design, the system must resist a 176 N load without pushing through the sheet metal opening at all operating temperatures.": "对于钩转式格栅,在所有工作温度下须承受176N载荷而不被推穿钣金开口。",
"Demonstrate the Robustness, in terms of Signal to Noise ratio, of each of the key functions selected relative to that of other systems/Components on the market.": "以信噪比衡量,证明所选各关键功能相对市场上其它系统/零件的稳健性。",
"Task breakdown validation (EMC, ESD, vibration, mechanical shock, functional, parametric, thermal, solar soak, chemical exposure, dust intrusion, etc.) --------->": "任务分解验证(EMC、ESD、振动、机械冲击、功能、参数、热、日照、化学暴露、灰尘侵入等)--------->",
"Measure gloss using 60 deg gloss meter or equivalent per ASTM D523": "用60°光泽计或按 ASTM D523 等效法测光泽",
"No fade or color change in excess of the #4 rating on the ISO Gray scale for evaluating change in color. No noticeable tackiness, separation, or other detrimental change.": "ISO 灰卡变色不超过4级;无明显发粘、分离或其它有害变化。",
"For textured and/or low gloss applications, there must be no whitening effects up to and including 10 newtons force. Moderate whitening is allowed at 15 and 20 newtons force.": "晒纹及/或低光泽件,≤10N 不得发白;15N、20N 允许中度发白。",
"No fade or color change in excess or #4-5 on the ISO gray scale for evaluation change in color and other detrimental change.": "ISO 灰卡变色不超过4-5级,且无其它有害变化。",
"No fade or color change in excess of #4-5 rating on the ISO gray Scale for evaluation change in color and no other detrimental change.": "ISO 灰卡变色不超过4-5级,且无其它有害变化。",
"All materials, procedures, processes, components, or systems must conform to the current regulatory (governmental) requirements regarding regulated substances and recycle ability.": "所有材料、程序、工艺、零件或系统须符合现行受管控物质与可回收性的法规(政府)要求。",
"State actual test results (including revisions to test quantity & timing) based on specified Acceptance Criteria (R83/C90, P92/C90, No failures, 1 of 4 samples failed, etc.).": "依据规定合格判据给出实际测试结果(含数量与时间的修订;如 R83/C90、P92/C90、无失效、4件中1件失效等)。",
"Acceptance Criteria": "合格判据", "Test Target": "测试目标",
"Specific Pass/Fail statement regarding the sample set (R90/C90, P90/C90, No Failures, etc.).": "关于样本组的具体合格/不合格陈述(如 R90/C90、P90/C90、无失效等)。",
"The time or performance value that each test sample must achieve.": "每个样件须达到的时间或性能值。",
"Identify and select the test strategy (Simulation or Physical Testing) that will be used to measure the functional robustness of the selected key functions (Outer Array – Signal and Noise Strategy)": "确定并选择用于衡量所选关键功能稳健性的测试策略(仿真或实物测试)(外阵列-信噪策略)",
"The part shall be exposed to 8 hours immersion followed by 16 hours min drying in room temperature per cycle.": "每循环:浸泡8小时,再于室温干燥至少16小时。",
"Cycle whole part 10 times.": "整件循环10次。", "Rinse samples to remove salt deposits.": "冲洗样件以去除盐沉积。",
"the requirements relative to the bonding of plastic parts such as plastic, in order to guarantee the holding of the part on the": "关于塑料件粘接的要求,以保证零件在",
"vehicle and the sealing performance.": "车辆上的固定及密封性能。",
"COMPONENT FEATURES HAVE STRONG CORRELATION TO VEHICLE LEVEL FIT/FINISH.": "零件特征与整车级配合/外观强相关。",
"MONTHLY 30-PIECE eCMM UPLOAD REQUIRED FOR LIFE OF VEHICLE PROGRAM.  DATA SHOULD BE COLLECTED FROM MULTIPLE 5-PIECE SUBGROUPS.": "整个车型生命周期内须每月上传30件 eCMM,数据应来自多个5件子组。",
"The product should meet build objective measurement by Jury Evaluation. There should be ample clearance from the accelerator pedal  (minimum 40mm) and brake/clutch pedals (minimum 10mm) at all pedal positions.": "产品须通过评审团评估达成制造目标;在所有踏板位置,与油门踏板(≥40mm)、刹车/离合踏板(≥10mm)须有充足间隙。",
"Identify and select the weight optimization strategy (CAE Topology Optimization software or Physical testing). For structural (load bearing) components or systems, a CAE topology optimization study is required.": "确定并选择轻量化策略(CAE 拓扑优化软件或实物测试);承载结构件/系统须做 CAE 拓扑优化研究。",
"Identify factors and levels that can be controlled  that result in the least variation in performance when tested in the presence of the uncontrolled factors (Robustness as quantified in a Signal to Noise ratio)": "识别在存在不可控因素时使性能波动最小的可控因素及水平(以信噪比量化稳健性)",
"Hood  vent / cladidngs must exhibit no breaks, separations or failures after completion of LP7N056, Misuse and Fatigue Test for hood": "完成 LP7N056(发盖误用与疲劳测试)后,发盖格栅/护板不得出现断裂、分离或失效",
"Also surrounding components must exhibit no damage due to contact with claddings.": "周边件也不得因与护板接触而受损。",
"Material should successfully withstand exposure of the required test procedures without displaying any significant staining, discoloration, gloss loss, swelling, distortion, or deterioration of the plastic surface.": "材料须经受规定测试而无明显沾污、变色、失光、溶胀、变形或塑料表面劣化。",
"Detailed description and task breakdown associated with each feature/function, including effort, duration, and resources required for each task (logic, flow, algorithm, HMI, CAN, Diagnostics, architecture, etc.) --------->": "各功能的详细描述与任务分解,含每项任务的工作量、工期、资源(逻辑、流程、算法、HMI、CAN、诊断、架构等)--------->",
"MONTHLY 30-PIECE eCMM UPLOAD REQUIRED.   SAMPLE SIZE MAY BE REDUCED TO 5 PIECES PER MONTH PENDING SUCCESSFUL LONG-TERM CAPABILITY ASSESSMENT.  ASSESSMENT CONDUCTED A MINIMUM OF 6 MONTHS AFTER START OF PRODUCTION.": "须每月上传30件 eCMM;若长期能力评估通过,可降至每月5件;评估在投产至少6个月后进行。",
"No degradation of attachments (broken and/or loose), no loss of form or function, no permanent deformation, no color or peeling of paint or chrome or other defects detrimental to appearance (separation between parts) is allowed": "不允许连接件劣化(断裂/松动)、形状或功能丧失、永久变形、漆/镀铬变色或剥落,以及其它有损外观的缺陷(件间分离)。",
"This requirement applies only if hood vent/ claddings lares and claddings are attached to sheet metal without mechanical fasteners.": "本要求仅适用于发盖格栅/护板未用机械紧固件而直接固定到钣金的情况。",
"The proposed system or change must meet or exceed the performance level attained by the current system.": "拟用系统或变更须达到或超过现有系统的性能水平。",
"Requirements are to be set by the various program groups, based on benchmarking results and inserted into each vehicle’s DVP&R.  There shall be no physical damage to parts or separation of the parts from the body after completion of the test.": "要求由各项目组依对标结果设定并写入各车型 DVP&R;测试后零件不得有物理损坏或与车身分离。",
"The quantifiable time or performance value that each test sample must achieve (i.e. < 22cc/m @ 5psi).": "每个样件须达到的可量化时间或性能值(如 <22cc/m @5psi)。",
"Specific statement regarding test requirements (i.e. R90/C90, R90C70, P90/C90, P99/C90, No Failures per requirements, etc.).": "关于测试要求的具体陈述(如 R90/C90、P90/C90、按要求无失效等)。",
"Results must be submitted and approved by engineer and materials engineer": "结果须提交并经工程师与材料工程师批准",
"Each component shall be clearly and indelibly marked with supplier identification, date of manufacture (as per Std. 0.00013), Trademark per Std. 07412, Identification of Supplier Code Std. 07610 and any other data as per drawing (e.g. material recycling marking as per Std. 07416) in the area specified on drawing (if applicable).": "每个零件须在图纸指定区域(如适用)清晰、不可擦除地标注:供应商标识、制造日期(按 Std.0.00013)、商标(按 Std.07412)、供应商代码(Std.07610)及图纸要求的其它信息(如材料回收标识,按 Std.07416)。",
"Gluing between two plastic parts (for example, between aesthetical skin and its reinforcement) must meet the following requirements:": "两塑料件之间的粘接(例如外观表皮与其加强件)须满足以下要求:",
"Engineer to complete the below Statement Of Work (SOW) as follows.": "工程师按以下要求填写下方工作说明书(SOW)。",
" 1) Complete all relevant fields (blue cells in Column \"C\") in the form below as applicable to the subject ED&D project. ": " 1) 按本 ED&D 项目情况,填写下表所有相关字段(C列蓝色单元格)。",
" 2) Specify the engineering requirements needed for the supplier to implement the feature required.": " 2) 明确供应商实现所需功能需满足的工程要求。",
" 3) Imbed attachments (incl. Pictures) as desired anywhere in this worksheet.": " 3) 可在本表任意处嵌入附件(含图片)。",
" 4) All blue cells are formatted to wrap text.": " 4) 所有蓝色单元格已设为自动换行。",
"Supplier to complete the below Statement Of Work (SOW) as follows:": "供应商按以下要求填写下方工作说明书(SOW):",
" 1) Complete all relevant fields in the form below as applicable to the subject ED&D project. ": " 1) 按本 ED&D 项目情况填写下表所有相关字段。",
" 2) Provide all technical details relevant for the development and release of the feature required.": " 2) 提供与所需功能开发及发布相关的全部技术细节。",
" 4) Once the information in this tab is provided, proceed to completing the \"ED&D PBD (Blank)\" tab and the \"Spending Curve (Blank) tab\".": " 4) 本页填好后,继续填写“ED&D PBD(空白)”页与“Spending Curve(空白)”页。",
"Surface shall not show significant discoloration or gloss change at or below the": "在以下载荷及以下时,表面不得有明显变色或光泽变化:",
"10 N load level. The test sample shall achieve a minimum of 4 on the AATCC Gray Scale. Surface of part may not stress whiten when exposed to 10N scratch pin": "10N载荷;样件 AATCC 灰卡须≥4级;10N划针下零件表面不得应力发白。",
"No discoloration, color tone or change in\nhue in excess of 4.5 of the AATCC Gray\nScale. Maximum 3.0 Delta E.\nReport Delta H, Delta C and L, a, b data.": "AATCC 灰卡变色/色调/色相变化不超过4.5级,ΔE≤3.0;报告 ΔH、ΔC 及 L、a、b 数据。",
"100% of continuity for each bead\n(no adhesive failure in the width)": "每条胶线100%连续(宽度方向无脱胶)",
"All other results must be submitted to\nus for evaluation.": "其它所有结果须提交我方评估。",
"Average quotation by side:": "按侧别平均报价:",
}
